git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editPreset: nvim
  openLink: open "$(echo "{{link}}" | sed 's/%2F/\//g')"
gui:
  theme:
    selectedLineBgColor:
    - "#363646"
