[[session]]
name = "ï“¢ home"
path = "~"

[[session]]
name = "ðŸ“¥ downloads"
path = "~/Downloads/"
startup_command = "y"

[[session]]
name = "î¯¥ dotfiles"
path = "~/dotfiles/"
startup_command = "nvim"

[[session]]
name = "î˜« nvim"
path = "~/dotfiles/config/nvim/"
startup_command = "nvim"

[[session]]
name = "ó°Žš scratches"
path = "~/dev/scratches/"
startup_command = "nvim"

[[session]]
name = "ó±‚› rest APIs"
path = "~/dev/rest-apis/"
startup_command = "nvim"
