[[session]]
name = "ðŸ“¥ Downloads"
path = "~/Downloads/"
startup_command = "y"

[[session]]
name = "î¯¥ Dotfiles"
path = "~/dotfiles/"
startup_command = "nvim"

[[session]]
name = "î˜« Nvim"
path = "~/dotfiles/config/nvim/"
startup_command = "nvim"

